// Safe Firebase bootstrap.
//
// Until `flutterfire configure` is run, the generated `firebase_options.dart`
// doesn't exist and calling Firebase.initializeApp() throws. This function
// tries to init lazily and reports the result via [FirebaseStatus] so the app
// still runs (in offline / placeholder mode) before backend wiring.
//
// After `flutterfire configure`, replace the body of [bootstrapFirebase] with:
//
//   await Firebase.initializeApp(
//     options: DefaultFirebaseOptions.currentPlatform,
//   );
//   return FirebaseStatus.ready;
//
// and uncomment the imports below.

import 'package:flutter_riverpod/flutter_riverpod.dart';

// import 'package:firebase_core/firebase_core.dart';
// import '../../firebase_options.dart';  // generated by `flutterfire configure`

enum FirebaseStatus {
  /// Firebase initialised — full feature set available.
  ready,

  /// `flutterfire configure` hasn't been run yet. App still runs in
  /// offline / placeholder mode.
  notConfigured,

  /// Init was attempted but threw. See logs.
  failed,
}

Future<FirebaseStatus> bootstrapFirebase() async {
  // TODO(setup): after `flutterfire configure`, replace this body with the
  // real init shown in the comment at the top of this file.
  return FirebaseStatus.notConfigured;
}

/// Read with `ref.watch(firebaseStatusProvider)` anywhere in the app to
/// branch on whether Firebase is wired up.
final firebaseStatusProvider = Provider<FirebaseStatus>((_) {
  throw UnimplementedError('Override in ProviderScope in main.dart');
});
