// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB4wO5vcP0d1Q6Fz_rrK4xKJxXQDJX9x1E',
    appId: '1:975719145676:web:160cff771b6b0625756269',
    messagingSenderId: '975719145676',
    projectId: 'photoapp-880ce',
    authDomain: 'photoapp-880ce.firebaseapp.com',
    storageBucket: 'photoapp-880ce.firebasestorage.app',
    measurementId: 'G-BJ51Q9X4CJ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCHWm1q0XncOjtKUfib40HZK7n0Opr4OIc',
    appId: '1:975719145676:android:ce75d5c86e6655db756269',
    messagingSenderId: '975719145676',
    projectId: 'photoapp-880ce',
    storageBucket: 'photoapp-880ce.firebasestorage.app',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyB4wO5vcP0d1Q6Fz_rrK4xKJxXQDJX9x1E',
    appId: '1:975719145676:web:9a2dbab4deb4444e756269',
    messagingSenderId: '975719145676',
    projectId: 'photoapp-880ce',
    authDomain: 'photoapp-880ce.firebaseapp.com',
    storageBucket: 'photoapp-880ce.firebasestorage.app',
    measurementId: 'G-1Q4FVVT5D7',
  );
}
